oquArnaWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from oquArnaWeb import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("staff/", views.custom_admin_home_view, name="custom_admin_home"),
    path("staff/actions/", views.actions_history_view, name="actions_history"),
    path("staff/report/", views.users_report_download, name="users_report_download"),
    path("staff/certificates/<int:course_id>/", views.download_course_certificates, name="download_course_certificates"),
    path("users/", include("users.urls")),
    path("works/", include("authors_works.urls")),

    path("", views.home_view, name="home"),

    path('accounts/', include('django.contrib.auth.urls')),# кастомная ссылка для активации
    path('courses/', include('courses.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import ActivateUserPasswordResetConfirmView

from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # активация учётной записи
    path(
        "activate/<uidb64>/<token>/",
        views.ActivateUserPasswordResetConfirmView.as_view(),
        name="activate",
    ),

    path('send_code', views.SendCodeToEmailView.as_view(), name='send-code'),

    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # профиль, аватар и документы
    path("profile/",               views.ProfileView.as_view(),     name="profile"),
    path("profile/avatar/",        views.UpdateAvatarView.as_view(), name="update-avatar"),
    path("profile/avatar/delete/", views.DeleteAvatarView.as_view(), name="delete-avatar"),

    path('entry_email/', views.EntryEmailView.as_view(), name='entry-email'),
    path('verification_code/', views.VerificationCodeView.as_view(), name='verification-code'),
    path('reset_password/', views.ResetPasswordView.as_view(), name='reset-password'),

    path('register_entry_email/', views.RegisterEntryEmailView.as_view(), name='register-entry-email'),
    path('register_verification_code/', views.RegisterVerificationCodeView.as_view(), name='register-verification-code'),
    path('register_set_password/', views.RegisterResetPasswordView.as_view(), name='register-set-password'),
    path('', views.HomeView.as_view(), name='home'),
    # документы пользователя
    path("profile/documents/",               views.DocumentsView.as_view() ,  name="documents"),
    path("profile/documents/delete/<int:pk>/", views.document_delete, name="document-delete"),

    # домашняя
    path("", views.HomeView.as_view(), name="home"),
]

templates/components/back_button.html
{% load static %}
{% if is_modal%}
    <button 
        class="rounded-2 border-0"
        data-bs-dismiss="modal">
        <img
            width="30"
            height="30"
            src="{% static 'icons/back.svg' %}"
            alt="логотип">
    </button>
{%else%}
    <a href="{{ href }}">
        <img
            width="30"
            height="30"
            src="{% static 'icons/back.svg' %}"
            alt="логотип">
    </a>
{%endif%}

templates/components/card_add.html
{%load static%}
{%if href_card_add%}
    <a class="card text-decoration-none cardShadow col d-flex flex-column p-0 border border-dark rounded-3 overflow-hidden"
        href="{% url href_card_add %}" >
        <div class="cardIconContainer modalBodyCellValue appThemeBorderColor d-flex justify-content-center align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
            </svg>
        </div>
        <p class="categoryName m-auto px-2 fw-bold">
            Создать...
        </p>
    </a>
{%else%}
    <div
        id="createCourseCard"
        class="card text-decoration-none cardShadow col d-flex flex-column p-0 border border-dark rounded-3 overflow-hidden">
        <div class="cardIconContainer modalBodyCellValue appThemeBorderColor d-flex justify-content-center align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
            </svg>
        </div>
        <p class="categoryName m-auto px-2 fw-bold">
            Создать...
        </p>
    </div>
    <script src="{% static 'courses/js/course-create-modal.js' %}">
    </script>
{%endif%}

templates/components/courseCard.html
{% if item.is_access %}
    <a
        class="card cardShadow"
        data-id="{{item.id}}"
        href="{% if request.user.is_educator %}{%url 'lessons' item.id %} {% else %} {%url 'lessons-student-list' item.id %} {% endif %}">
        <div class="appThemeColorBackground  d-flex align-items-center justify-content-center flex-shrink-0 h-25 text-center text-light">
            <p class="fs-6">
                {{ item.name }}
            </p>
        </div>
        <div class="d-flex flex-column justify-content-evenly flex-shrink-0 h-50 p-2">
            <p class="text-truncate">
                <span>Автор:</span> {{ item.creator.full_name }}
            </p>
        </div>
        <div class="container flex-shrink-0 h-25 p-0">
            <div class="row">
                <div class="col">
                </div>
                <div class="col d-grid" style="grid-template-columns: 1fr 1fr; grid-auto-rows: 50%; gap: 3px">
                    <div
                        class="px-2"
                        style="grid-row: span 2">
                        <p class="coursePeriodBadge mb-0">Период курса:</p>
                    </div>
                    <div>
                        <span class="coursePeriodDate">{{ item.start_date|date:"d.m.Y" }}</span>
                    </div>
                    <div>
                        <span class="coursePeriodDate">{{ item.end_date|date:"d.m.Y" }}</span>
                    </div>
                </div>
            </div>
        </div>
    </a>
{% else %}
    <div
        class="card cardShadow"
        data-bs-toggle="modal"
        data-bs-target="#entityModal"
        data-id="{{item.id}}">
        <div class="appThemeColorBackground  d-flex align-items-center justify-content-center flex-shrink-0 h-25 text-center text-light">
            <p class="fs-6">
                {{ item.name }}
            </p>
        </div>
        <div class="d-flex flex-column justify-content-evenly flex-shrink-0 h-50 p-2">
            <p class="text-truncate">
                <span>Автор:</span> {{ item.creator.full_name }}
            </p>
        </div>
        <div class="container flex-shrink-0 h-25 p-0">
            <div class="row">
                <div class="col">
                </div>
                <div class="col d-grid" style="grid-template-columns: 1fr 1fr; grid-auto-rows: 50%; gap: 3px">
                    <div
                        class="px-2"
                        style="grid-row: span 2">
                        <p class="coursePeriodBadge mb-0">Период курса:</p>
                    </div>
                    <div>
                        <span class="coursePeriodDate">{{ item.start_date|date:"d.m.Y" }}</span>
                    </div>
                    <div>
                        <span class="coursePeriodDate">{{ item.end_date|date:"d.m.Y" }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/components/createCourseCard.html
{%load static%}
<div class="card cardShadow col d-flex flex-column p-0 border border-dark rounded-3 overflow-hidden">
    <div class="cardIconContainer modalBodyCellValue appThemeBorderColor d-flex justify-content-center align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3z"/>
        </svg>
    </div>
    <p class="categoryName m-auto px-2 fw-bold">
        Создать...
    </p>
</div>

templates/components/entitiesTabs.html
<div class="d-flex flex-row w-50 m-auto justify-content-evenly">
    {%include 'components/entityHeader.html' with entity_name="Все курсы" is_active=True%}
    {%include 'components/entityHeader.html' with entity_name="Мои курсы" is_active=False%}
</div>

templates/components/entities_or_categories_list.html
<div class="container-fluid cardContainer w-75 overflow-y-auto fw-bold">
    <div class="row row-cols-4 g-4">
        <div class="col">
            {%include 'components/createCourseCard.html'%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
        <div class="col">
            {%include template_name%}
        </div>
    </div>
</div>
<div 
    id="entityModal"
    class="modal fade"
    tabindex="-1"
    aria-labelledby="entityModal"
    aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content appThemeBorderColor rounded-4">
            <div class="modal-header appThemeBorderColor position-relative rounded-3">
                <p class="modal-title position-absolute top-25 start-50 translate-middle-x fs-5 text-center fw-bold" id="entityModalLabel">
                    Английский язык (Intermediate) 
                </p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body appGrayColorBackground p-5 fw-bold">
                <textarea
                    class="form-control appThemeBorderColor"
                    readonly>Привет! Это описание</textarea>
                <div class="container my-4 p-0 text-center">
                    <div class="row gx-5">
                        <div class="col-md-6">
                          <div class="d-flex flex-column gap-3 h-100">
                            <div class="modalBodyCell appThemeColorBackground text-light fs-5 d-flex justify-content-center align-items-center rounded-2">
                                Категория курса:
                            </div>
                            <div class="modalBodyCell appThemeColorBackground text-light fs-5 d-flex justify-content-center align-items-center rounded-2">
                              Даты проведения:
                            </div>
                            <div class="modalBodyCell appThemeColorBackground text-light fs-5 d-flex justify-content-center align-items-center rounded-2">
                              Кол-во участников:
                            </div>
                            <div class="modalBodyCell appThemeColorBackground text-light fs-5 d-flex justify-content-center align-items-center rounded-2">
                              Автор курса:
                            </div>
                            <div class="modalBodyCell appThemeColorBackground text-light fs-5 d-flex justify-content-center align-items-center rounded-2">
                              Темы курса:
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="d-flex flex-column gap-3 h-100">
                            <div class="modalBodyCell modalBodyCellValue bg-light fs-5 d-flex justify-content-center align-items-center rounded-4">
                                Категория
                            </div>
                            <div class="modalBodyCell modalBodyCellValue bg-light fs-5 d-flex justify-content-center align-items-center rounded-4">
                              11.03.2025<br />11.03.2025
                            </div>
                            <div class="modalBodyCell modalBodyCellValue bg-light fs-5 d-flex justify-content-center align-items-center rounded-4">
                              23
                            </div>
                            <div class="modalBodyCell modalBodyCellValue bg-light fs-5 d-flex justify-content-center align-items-center rounded-4">
                              Дамир Мертл
                            </div>
                            <div class="modalBodyCell modalBodyCellDownload bg-light fs-5 d-flex justify-content-center align-items-center w-50 m-auto rounded-4">
                              Скачать
                            </div>
                          </div>
                        </div>
                      </div> 
                </div>
            </div>   
        </div>
    </div>
</div>

templates/components/entities_tabs.html
<div class="d-flex flex-row w-50 m-auto justify-content-evenly">

    {% if active_table_name == "one_table" %}
        {%include 'components/entity_header.html' with entity_name=tab_name_one is_active=True url=url_one%}
        {%include 'components/entity_header.html' with entity_name=tab_name_two is_active=false url=url_two%}
    {% elif active_table_name == "two_table" %}
        {%include 'components/entity_header.html' with entity_name=tab_name_one is_active=False url=url_one%}
        {%include 'components/entity_header.html' with entity_name=tab_name_two is_active=True url=url_two%}
    {% endif %}


</div>

templates/components/entityHeader_selected.html
<h1 class="text-center my-2">
    <span
        id="courseCategoryHeader"
        class="d-inline-block w-25 border border-white badge text-white rounded-3">
        {{ entity_name }}
    </span>
</h1>

templates/components/entity_header.html
<h1 class="text-center  my-2">
    {%if is_active%}
        <a
            class="pageHeader text-decoration-none appThemeColorBackground px-5 d-inline-block border border-white badge text-white rounded-3"
            data-active="{{ is_active }}"
            href={{ url }}>
            {{ entity_name }}
        </a>
    {%else%}
        <a
            class="pageHeader text-decoration-none d-inline-block px-5 border border-white badge text-bg-light text-dark rounded-3 shadow"
            data-active="{{ is_active }}"
            href={{ url }}>
            {{ entity_name }}
        </a>
    {%endif%}
</h1>

templates/components/entity_header_selected.html
<h1 class="text-center my-2">
    <span
        id="courseCategoryHeader"
        class="d-inline-block w-25 border border-white badge text-white rounded-3">
        {{ entity_name }}
    </span>
</h1>

templates/components/message.html
<script>
    function showMessage() {
        const error = document.getElementById("message");
        setTimeout(() => {
            error.remove();
        }, 10000);
    }
</script>
<div id="messageContainer">
    {% if messages %}
        {% for message in messages %}
        <div
            id="message"
            class="message {% if 'error' in message.tags %} error {% elif 'success' in message.tags %} success {% endif %}  d-flex flex-column align-items-center">
            <span class="error-text">
                {{ message }}
            </span>
        </div>
        {% endfor %}
    <script>
        showMessage();
    </script>
    {% endif %}
</div>

templates/components/name_page.html
{% load static %}

<div class="d-flex align-items-center justify-content-between w-100 px-4">
    {% if href %}
        {% include 'components/back_button.html' with href=href %}
    {% else %}
        {% include 'components/back_button.html' with href="javascript:history.back()" %}
    {% endif %}
    <h3 class="text-white">{{ name }}</h3>
    <div></div>
</div>

templates/components/navbar.html
{% load static %}

<script>
    const menuItems = [
        {
            name: 'personal_account',
            title : 'Личный кабинет',
            icon: '{% static "icons/personal_account.svg" %}',
            href: "{% url 'users:profile' %}"
        },
        {
            name: 'author_works',
            title : 'Авторские работы',
            icon: '{% static "icons/authors_works.svg" %}',
            href: "{% url 'author-categories' %}"
        },
        {
            name: 'course',
            title : 'Учебные курсы',
            icon: '{% static "icons/course.svg" %}',
            href: "{% url 'courses-categories' %}"
        },
        {
            name: 'schedule',
            title : 'Расписание',
            icon: '{% static "icons/create_entry.svg" %}',
            href: "{% url 'schedule' %}"
        }
    ];
</script>

<script src="{% static 'js/navbar.js' %}"></script>

templates/components/search.html
<form method="get" class="d-flex align-self-center justify-content-between w-100 px-4">
    {% block search_form %}
    {% endblock %}
    {% if href_back %}
        {% include 'components/back_button.html' with href=href_back %}
    {% else %}
        <div></div>
    {% endif %}
    <input type="text" class="search" name="search" placeholder="Поиск..." value="{{ request.GET.search|default:'' }}">
    <div></div>
</form>